server:
  port: 9090


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  application:
    name: cgk-gateway-server


  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: cgk-libro
              uri: lb://cgk-libro
              predicates:
                - Path=/libros/**

            - id: cgk-usuario
              uri: lb://cgk-usuario
              predicates:
                - Path=/usuarios/**

            - id: cgk-prestamo
              uri: lb://cgk-prestamo
              predicates:
                - Path=/prestamos/**


